### PR TITLE
Resize icon to multiple sizes

### PR DESCRIPTION
**Pull request by palvarez89**

### CODE REVIEW

**Comment by palvarez89** [comment]
The `convert` tool is not available in the build environment. Closing.

**Comment by cpba** [comment]
@palvarez89  In order to use convert the way you want you'd need to build imagemagick and then clean it up.

It's not hard to do, I used to do it for a different project:

https://github.com/flathub/im.srain.Srain/blob/1ba2909dfef7f79dd6ea7a92bf500edaff9c0ddf/im.srain.Srain.yaml#L26-L32

The only issue is that imagemagick is a big project and it adds a lot to the build time, I wouldn't want to add it without a good reason.

Does the current icon size produce any tangible issues that would merit including it?

**Comment by palvarez89** [comment]
It seems to take less than 2 minutes to build `imagemagick`, the results are not great though. Maybe a lower resolution is being used on this dock.

Screenshot:

atom-icon-new

**Comment by cpba** [comment]
Using an svg icon would certainly be more practical and may produce better results, they are way easier to resize and the sdk already includes rsvg.

However, it's unlikely to look any better than your example, most old gnome icons look fine at very low resolutions, but that's because the lower resolution versions are hand-crafted. A detailed depiction of an atom doesn't scale down all that well :(

**Comment by cpba** [comment]
I found an svg icon in the wikimedia commons and put together a quick experiment. I don't have much faith in this but I figured it wouldn't hurt to try.

@palvarez89 Could you please install [the last test build](http://repo-test.flathub.org:8080/build-repo/1952/io.atom.Atom.flatpakref) and tell me if it helps matters in any way?

**Comment by palvarez89** [comment]
@cpba Yeah, I don't know if it's because you are also creating an smaller version of the icon, or because it comes from an SVG, but it looks way better:

atom-screenshot-svg

Also, we wouldn't depend on `imagemagick`, which is great. The bad side of this is that Atom doesn't provide any svg's in the package. What would be the right approach if we wanted to implement correctly this experiment?

**Comment by cpba** [comment]
@palvarez89 not sure how I missed this but upstream actually has a set of already resized icons:

https://github.com/atom/atom/tree/master/resources/app-icons/stable/png

These are all included in the official rpm package, but for some reason the tarball and the deb package that this manifest builds from only bundle a single 1024px icon. I'm not sure if they are doing this on purpose.

Easiest solution at this point would be to grab the icons from the rpm, although it should maybe be reported upstream just in case they consider this a bug.

**Comment by cpba** [comment]
I think I've got it this time.

@palvarez89 could you please try out [test build 2106](http://repo-test.flathub.org:8080/build-repo/2007/io.atom.Atom.flatpakref) to ensure that it solves your issue?

**Comment by palvarez89** [comment]
It does look great!

atom-from-rpm

**Pull request merged**
