### PR TITLE
Update AppStream

### PR DESCRIPTION
**Pull request by FakeShemp**

### CODE REVIEW

**Comment by FakeShemp** [comment]
`Error loading desktop file: Failed to find icon: Failed to find icon io.atom.Atom`
Is 1024x1024 not a supported resolution? It's the only resolution supplied by the installation package.

**Comment by cpba** [comment]
I honestly don't know, I've never tried it and I didn't find any reference to it in the spec.

I'll take a look around and see what I find.

**Comment by cpba** [comment]
Sorry to take so long, I've asked about the matter and buildbot only supports the resolutions specified in the hicolor icon theme, 512x512 being the highest. Technically it does go higher than that, with things like 512x512@2 being used in hidpi scenarios.

At any rate, there is an issue as you noted where the deb package only supplies a 1024x1024 icon, I've worked around this by using icons from the rpm package instead. This should solve the resolution issues that you were in part trying to fix here.

@FakeShemp Do you still want to proceed with this merge request?

**Comment by FakeShemp** [comment]
Not if you fixed it elsewhere. 🙂

**Comment by hfiguiere** [comment]
closing then. Reopen if you feel it needs fixing.

**Pull request closed without merging**
