### PR TITLE
Update Atom to 1.63.1

### PR DESCRIPTION
**Pull request by farribeiro**

### CODE REVIEW

**Comment by farribeiro** [comment]
bot,build

**Comment by farribeiro** [comment]
bot, build

**Comment by farribeiro** [comment]
needs update also the Electron BaseAPP

**Comment by cpba** [comment]
Thank you.

**Comment by Tamaranch** [comment]
@cpba Although this has been merged, the version available on Flathub is still 1.60.0. Is something missing?

**Comment by farribeiro** [comment]
need changes the appstream, just this, iirc

**Comment by cpba** [comment]
The version on flathub is 1.63.1, it's just that this pr didn't update the
metadata, I'll try to remember to do it when I get home.

El dl., 30 de gen. 2023, 13:55, Gaël Bonithon ***@***.***> va
escriure:

**Comment by Tamaranch** [comment]
Ah yes indeed, the flatpak is at 1.63.1 after update. Thanks! :)

**Pull request merged**
