### PR TITLE
Update to Freedesktop 22.08

### PR DESCRIPTION
**Pull request by darkdragon-001**

### CODE REVIEW

**Comment by darkdragon-001** [comment]
bot, build

**Comment by cpba** [comment]
Thank you for the help.

This builds but it won't run because it's trying to run `/app/bin/atom-real` (which is a shell script, despite the name) through `zypak-wrapper`, and newer versions of zypak only support actual binaries.

**Comment by cpba** [comment]
Now this is the same as #134, except it builds zypak rather than using the already bundled one.

The problem is that now it crashes on start just like #134 does, with the same message:
```[2:0928/120703.675652:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.```

**Comment by darkdragon-001** [comment]
See #134

**Pull request closed without merging**
