### PR TITLE
Bump runtime to 21.08

### PR DESCRIPTION
**Pull request by cpba**

### CODE REVIEW

**Comment by jonathancross** [comment]
@cpba Are you looking into [the errors](https://flathub.org/builds/#/builders/35/builds/9059)?

**Comment by cpba** [comment]
bot, build

**Comment by darkdragon-001** [comment]
Looks like `clang++` is not found :thinking:

**Comment by darkdragon-001** [comment]
Maybe you also need to update `zypak` to the latest version `v2022.04`?

**Pull request closed without merging**
